### ISSUE TITLE
A Bug on Pre-processing Pubmed Dataset

### ISSUE THREAD

**Issue by Haicang** [hengruizhang98/mvgrl#3]
When I use the code on Pubmed dataset. I get the following error.

```Traceback (most recent call last):
  File "/home_nfs/haicang/repos/self-supervised-gnns/mvgrl-dgl/node/main_sample.py", line 100, in <module>
    out = model(g, dg, f, sf, ew)
  File "/home_nfs/haicang/lib/miniconda3/envs/rnet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home_nfs/haicang/repos/self-supervised-gnns/mvgrl-dgl/node/model.py", line 58, in forward
    h1 = self.encoder1(graph, feat)
  File "/home_nfs/haicang/lib/miniconda3/envs/rnet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home_nfs/haicang/lib/miniconda3/envs/rnet/lib/python3.10/site-packages/dgl/nn/pytorch/conv/graphconv.py", line 408, in forward
    raise DGLError(
dgl._ffi.base.DGLError: There are 0-in-degree nodes in the graph, output for those nodes will be invalid. 
This is harmful for some applications, causing silent performance regression. 
Adding self-loop on the input graph by calling `g = dgl.add_self_loop(g)` will resolve the issue. 
Setting ``allow_zero_in_degree`` to be `True` when constructing this module will suppress the check and let the code run.
```

Then I check the code of `process_dataset_appnp` in file `dataset.py`. I find self-loops are only added to the diff_graph. By adding `graph = dgl.add_self_loop(graph)` at the end of the function, the code works.

Btw, I guess the original code does not work due to updates of the DGL function `add_self_loop`.

**Comment by hengruizhang98** [comment]
Thanks! I've fixed this bug according to your suggestions.
